Repository buildtool/build-tools, pull requests merged in 2025-04, with the labels that each got.

#1071 chore(deps): update Go version to 1.24.2 in go.mod
  go.mod
Labels: ignore-for-release

#1079 fix(build): handle error comparison correctly in main
  cmd/build/build.go
Labels: bug

#1080 feat(build): add support to use StdIn for reading Dockerfile content
  pkg/args/args.go
  pkg/build/build.go
  pkg/build/build_test.go
  www/docs/commands/build.md
Labels: feature

#1081 chore(deps): update pre-commit hook versions
  .pre-commit-config.yaml
Labels: ignore-for-release

#1082 feat: add support for Azure Container Registry (ACR)
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/registry_test.go
  pkg/registry/acr.go
  pkg/registry/acr_test.go
  www/docs/config/registry.md
Labels: feature

#1088 chore: update aws-iam-authenticator to version 0.7.2
  Dockerfile
Labels: ignore-for-release

#1089 feat(docker): update base image to debian bookworm
  Dockerfile
Labels: feature
